"""情報収集ソース設定"""

SOURCES = [
    # ── 日本語サイト ─────────────────────────────────────────────────
    {
        "id": "thaich_news",
        "name": "タイランドハイパーリンクス",
        "type": "rss",
        "url": "https://www.thaich.net/news/rss.xml",
        "category": "ja_news",
        "max_items": 20,
        "lang": "ja",
    },
    {
        "id": "xbomber_news",
        "name": "X-BOMBER Thailand",
        "type": "rss",
        "url": "https://x-bomberth.com/feed/",
        "category": "ja_news",
        "max_items": 20,
        "lang": "ja",
    },
    {
        "id": "runbkk_net",
        "name": "タイ一択",
        "type": "rss",
        "url": "https://runbkk.net/feed/",
        "category": "ja_news",
        "max_items": 15,
        "lang": "ja",
    },

    # ── Thailand Privilege ────────────────────────────────────────────
    # 公式サイトはログイン必須のため代替ソースを複数設定
    # fetch_sources.py が取得できたものを優先して使う
    {
        "id": "privilege_tatnews",
        "name": "Thailand Privilege（TAT News）",
        "type": "rss",
        "url": "https://www.tatnews.org/category/thailand-privilege/feed/",
        "category": "privilege",
        "max_items": 10,
        "lang": "en",
    },
    {
        "id": "privilege_gnews",
        "name": "Thailand Privilege（Google News）",
        "type": "rss",
        "url": "https://news.google.com/rss/search?q=%22Thailand+Privilege+Card%22+news+update&hl=en&gl=TH&ceid=TH:en",
        "category": "privilege",
        "max_items": 10,
        "lang": "en",
    },

    # ── タイ語ニュース ────────────────────────────────────────────────
    {
        "id": "thairath_general",
        "name": "ไทยรัฐ（タイラット）",
        "type": "rss",
        "url": "https://www.thairath.co.th/rss/news.xml",
        "category": "news_pending",
        "max_items": 20,
        "lang": "th",
    },
    {
        "id": "khaosod_general",
        "name": "ข่าวสด（カーオソット）",
        "type": "rss",
        "url": "https://www.khaosod.co.th/feed",
        "category": "news_pending",
        "max_items": 20,
        "lang": "th",
    },
    {
        "id": "matichon_general",
        "name": "มติชน（マティチョン）",
        "type": "rss",
        "url": "https://www.matichon.co.th/feed",
        "category": "news_pending",
        "max_items": 15,
        "lang": "th",
    },
    {
        "id": "sanook_news",
        "name": "สนุก！ニュース",
        "type": "rss",
        "url": "https://news.sanook.com/rss/news.xml",
        "category": "news_pending",
        "max_items": 15,
        "lang": "th",
    },
    {
        "id": "kapook_news",
        "name": "กระปุก（カプック）",
        "type": "rss",
        "url": "https://news.kapook.com/rss.xml",
        "category": "news_pending",
        "max_items": 15,
        "lang": "th",
    },
    {
        "id": "dailynews",
        "name": "เดลินิวส์（デーリーニュース）",
        "type": "rss",
        "url": "https://www.dailynews.co.th/feed/",
        "category": "news_pending",
        "max_items": 15,
        "lang": "th",
    },

    # ── イベント情報 ─────────────────────────────────────────────────
    {
        "id": "tat_events",
        "name": "TAT公式イベント",
        "type": "rss_fulltext",
        "url": "https://www.tatnews.org/category/thailand-events-festivals/feed/",
        "category": "events",
        "max_items": 10,
        "lang": "en",
    },
    {
        "id": "bk_events",
        "name": "BK Magazine イベント",
        "type": "rss_fulltext",
        "url": "https://bk.asia-city.com/things-to-do/more-event-news/feed",
        "category": "events",
        "max_items": 5,
        "lang": "en",
    },
    {
        "id": "coconuts_bkk",
        "name": "Coconuts Bangkok",
        "type": "rss_fulltext",
        "url": "https://coconuts.co/bangkok/feed/",
        "category": "events",
        "max_items": 10,
        "lang": "en",
    },
    {
        "id": "nation_events",
        "name": "Nation Thailand イベント",
        "type": "rss_fulltext",
        "url": "https://www.nationthailand.com/feed/rss",
        "category": "events",
        "max_items": 10,
        "lang": "en",
    },

    # ── モールイベント ────────────────────────────────────────────────
    {
        "id": "emsphere_rss",
        "name": "EmSphere / EmQuartier イベント",
        "type": "rss_fulltext",
        "url": "https://emsphere.co.th/category/event/feed/",
        "category": "mall_events",
        "max_items": 15,
        "lang": "th",
    },
    {
        "id": "emdistrict_rss",
        "name": "EM District プロモーション",
        "type": "rss_fulltext",
        "url": "https://emsphere.co.th/category/promotion/feed/",
        "category": "mall_events",
        "max_items": 10,
        "lang": "th",
    },
    {
        "id": "thaiticket_uoblive",
        "name": "UOB Live（EmSphere）コンサート",
        "type": "scrape_structured",
        "url": "https://www.thaiticketmajor.com/venue/uob-live-emsphere.html",
        "category": "mall_events",
        "max_items": 15,
        "lang": "th",
        "scrape_rules": {
            "item_selector": ".event-item, .concert-item, article, .card",
            "title_selector": "h2, h3, .title, .event-name",
            "date_selector":  ".date, time, .event-date",
            "link_selector":  "a",
        },
    },
    {
        "id": "iconsiam_gnews",
        "name": "ICONSIAM イベント",
        "type": "rss_fulltext",
        "url": "https://news.google.com/rss/search?q=ICONSIAM+%E0%B8%81%E0%B8%B4%E0%B8%88%E0%B8%81%E0%B8%A3%E0%B8%A3%E0%B8%A1+2569&hl=th&gl=TH&ceid=TH:th",
        "category": "mall_events",
        "max_items": 8,
        "lang": "th",
    },
    {
        "id": "centralworld_gnews",
        "name": "CentralWorld イベント",
        "type": "rss_fulltext",
        "url": "https://news.google.com/rss/search?q=CentralWorld+%E0%B8%81%E0%B8%B4%E0%B8%88%E0%B8%81%E0%B8%A3%E0%B8%A3%E0%B8%A1+2569&hl=th&gl=TH&ceid=TH:th",
        "category": "mall_events",
        "max_items": 8,
        "lang": "th",
    },
    {
        "id": "siamparagon_gnews",
        "name": "Siam Paragon イベント",
        "type": "rss_fulltext",
        "url": "https://news.google.com/rss/search?q=%E0%B8%AA%E0%B8%A2%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%B2%E0%B8%A3%E0%B8%B2%E0%B8%81%E0%B8%AD%E0%B8%99+%E0%B8%81%E0%B8%B4%E0%B8%88%E0%B8%81%E0%B8%A3%E0%B8%A3%E0%B8%A1+2569&hl=th&gl=TH&ceid=TH:th",
        "category": "mall_events",
        "max_items": 8,
        "lang": "th",
    },
    {
        "id": "onebangkok_gnews",
        "name": "One Bangkok イベント",
        "type": "rss_fulltext",
        "url": "https://news.google.com/rss/search?q=%22One+Bangkok%22+%E0%B8%81%E0%B8%B4%E0%B8%88%E0%B8%81%E0%B8%A3%E0%B8%A3%E0%B8%A1+2569&hl=th&gl=TH&ceid=TH:th",
        "category": "mall_events",
        "max_items": 8,
        "lang": "th",
    },
]

MULTI_EVENT_SOURCES = {"tat_events", "bk_events"}
FILTER_FOR_EVENTS_SOURCES = {"coconuts_bkk", "nation_events"}

CATEGORY_LABELS = {
    "ja_news":       "日本語サイト",
    "privilege":     "Thailand Privilege",
    "news_domestic": "国内ニュース",
    "news_intl":     "国際ニュース",
    "events":        "イベント・祭り",
    "mall_events":   "モールイベント",
}
